- name: ----- Run timescale container -----
  docker_container:
    name: timescaledb
    image: "{{ NEXUS_ADDRESS }}:8085/timescale/timescaledb:2.4.2-pg13"
    volumes:
      - timescaledb---var-lib-postgresql-data:/var/lib/postgresql/data:rw
    env:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: Qu8mjdWd
      POSTGRES_DB: monit_zabbix
    ports:
      - 5432:5432
    command: -N 100
    restart_policy: unless-stopped
    tty: yes
    state: started
  tags: [postgres_ts_container]
