all:
  hosts:
    Mikrotik1:
      ansible_host: 192.168.20.1
      access_ip: 192.168.20.1
    Mikrotik2:
      ansible_host: 192.168.20.2
      access_ip: 192.168.20.2

    Mattermost:
      ansible_host: 192.168.20.40
      access_ip: 192.168.20.40

    Nexus:
      ansible_host: 192.168.20.20
      access_ip: 192.168.20.20
    IDS:
      ansible_host: 192.168.20.23
      access_ip: 192.168.20.23

    LoadBalancer1:
      ansible_host: 192.168.20.101
      access_ip: 192.168.20.101
    LoadBalancer2:
      ansible_host: 192.168.20.102
      access_ip: 192.168.20.102
    LoadBalancer3:
      ansible_host: 192.168.20.103
      access_ip: 192.168.20.103

    Sentry:
      ansible_host: 192.168.30.29
      access_ip: 192.168.30.29

    Master1:
      ansible_host: 192.168.30.51
      access_ip: 192.168.30.51
    Master2:
      ansible_host: 192.168.30.52
      access_ip: 192.168.30.52
    Master3:
      ansible_host: 192.168.30.53
      access_ip: 192.168.30.53

    Worker1:
      ansible_host: 192.168.30.61
      access_ip: 192.168.30.61
    Worker2:
      ansible_host: 192.168.30.62
      access_ip: 192.168.30.62
    Worker3:
      ansible_host: 192.168.30.63
      access_ip: 192.168.30.63
    
    NFS:
      ansible_host: 192.168.30.70
      access_ip: 192.168.30.70
    NFSBackup:
      ansible_host: 192.168.30.71
      access_ip: 192.168.30.71
  

    ZabbixDB:
      ansible_host: 192.168.40.124
      access_ip: 192.168.40.124
    PrometheusDB:
      ansible_host: 192.168.40.126
      access_ip: 192.168.40.126

    Kibana:
      ansible_host: 192.168.50.28
      access_ip: 192.168.50.28
    Elastic1:
      ansible_host: 192.168.50.81
      access_ip: 192.168.50.81
    Elastic2:
      ansible_host: 192.168.50.82
      access_ip: 192.168.50.82
    Elastic3:
      ansible_host: 192.168.50.83
      access_ip: 192.168.50.83


    Ansible:
      ansible_connection: local
    Sonarqube:
      ansible_host: 192.168.60.27
      access_ip: 192.168.60.27
    Jenkins:
      ansible_host: 192.168.60.30
      access_ip: 192.168.60.30
    JenkinsBuilderGlobal:
      ansible_host: 192.168.60.31
      access_ip: 192.168.60.31
    JenkinsBuilderBackup:
      ansible_host: 192.168.60.32
      access_ip: 192.168.60.32
    Gitlab:
      ansible_host: 192.168.60.35
      access_ip: 192.168.60.35

    Zabbix:
      ansible_host: 192.168.70.24
      access_ip: 192.168.70.24
    Grafana:
      ansible_host: 192.168.70.25
      access_ip: 192.168.70.25
    Prometheus:
      ansible_host: 192.168.70.26
      access_ip: 192.168.70.26

  children:
    Internet:
      hosts:
        Nexus:
        IDS:
        Mattermost:
        LoadBalancer[1:3]:
      vars:
        NEXUS_ADDRESS: 192.168.20.20
        ZABBIX_ADDRESS: 192.168.20.24
        NTP_ADDRESS: 192.168.20.2
      children:
        LoadBalancers:
          hosts:
            LoadBalancer[1:3]:

    K8s:
      hosts:
        Sentry:
        Master[1:3]:
        Worker[1:3]:
        NFS:
        NFSBackup:
      vars:
        NEXUS_ADDRESS: 192.168.30.20
        ZABBIX_ADDRESS: 192.168.30.24
        NTP_ADDRESS: 192.168.30.2
      children:
        AllNodes:
            Master[1:3]:
            Worker[1:3]:
        Masters:
          hosts:
            Master[1:3]:
        Workers:
          hosts:
            Worker[1:3]:
    
    DB:
      hosts:
        ZabbixDB:
        PrometheusDB:
      vars:
        NEXUS_ADDRESS: 192.168.40.20
        ZABBIX_ADDRESS: 192.168.40.24
        NTP_ADDRESS: 192.168.40.2

    Indexing:
      hosts:
        Kibana:
          Elastic[1:3]:
      vars:
        NEXUS_ADDRESS: 192.168.50.20
        ZABBIX_ADDRESS: 192.168.50.24
        NTP_ADDRESS: 192.168.50.2
      children:
        Elastics:
          hosts:
            Elastic[1:3]:

    Deployment:
      hosts:
        Ansible:
        Jenkins:
        JenkinsBuilderGlobal:
        JenkinsBuilderBackup:
        Sonarqube:
        Gitlab:
      vars:
        NEXUS_ADDRESS: 192.168.60.20
        ZABBIX_ADDRESS: 192.168.60.24
        NTP_ADDRESS: 192.168.60.2
      children:
        JenkinsBuilders:
          hosts:
            JenkinsBuilderGlobal:
            JenkinsBuilderBackup:

    Monitoring:
      hosts:
        Zabbix:
        Grafana:
        Prometheus:
      vars:
        NEXUS_ADDRESS: 192.168.70.20
        ZABBIX_ADDRESS: 192.168.70.24
        NTP_ADDRESS: 192.168.70.2

    DockerHosts:
      hosts:
        Mattermost:
        Nexus:
        ZabbixDB:
          AGENT_HOST_METADATA: LinuxDockerPostgres
        PrometheusDB:
          AGENT_HOST_METADATA: LinuxDockerPostgres
        Zabbix:
        Grafana:
        Prometheus:
      vars:
        AGENT_HOST_METADATA: LinuxDocker

    Mikrotik:
      hosts:
        Mikrotik[1:2]:
          AGENT_HOST_METADATA:

  vars:
    AGENT_HOST_METADATA: Linux
