- name: ----- Run postgres container -----
  docker_container:
    name: postgres-server
    image: "{{ NEXUS_ADDRESS }}:8085/postgres:13.4-alpine"
    volumes: 
      - postgres---var-lib-postgresql-data:/var/lib/postgresql/data:rw
    env:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pwd
      POSTGRES_DB: zabbix
    ports:
      - 5432:5432
    restart_policy: unless-stopped
    tty: yes
    state: started
  tags: [postgres_container]
