---
- name: ----- Install Java Development Kit and Elasticsearch -----
  apt:
    name: "{{ item }}"
    update_cache: yes
  loop:
    - elasticsearch
  tags: [install_packages]

- name: ----- Change the elasticsearch config file using template module -----
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
  notify: ----- Enable and Start Elasticsearch -----
  tags: [change_config]
