---
- name: ----- Run grafana container -----
  docker_container:
    name: grafana
    image: "{{ NEXUS_ADDRESS }}:8085/grafana/grafana-oss:8.3.3"
    ports:
      - 3000:3000
    volumes:
      - grafana---var-lib-grafana:/var/lib/grafana:rw
    restart_policy: unless-stopped
    tty: yes
    state: started
  tags: [grafana_container]
