---
- name: ----- Copy config.conf to mikrotik -----
  command: scp -P 2122 /home/ansible/provision/roles/mikrotik/files/config.rsc devops@192.168.20.250:/

- name: ----- Import the configuration -----
  routeros_command:
    commands:
      - import config.rsc
